# Copyright 2026 Quartile (https://www.quartile.co)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Product Odoo Module",
    "category": "Productivity",
    "license": "AGPL-3",
    "author": "Quartile",
    "website": "https://www.quartile.co",
    "version": "16.0.1.0.0",
    "depends": ["product"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/module_business_impact_data.xml",
        "data/module_complexity_data.xml",
        "data/module_license_data.xml",
        "data/module_popularity_data.xml",
        "data/module_source_type_data.xml",
        "data/product_attribute_data.xml",
        "views/customer_module_info_views.xml",
        "views/module_business_impact_views.xml",
        "views/module_complexity_views.xml",
        "views/module_license_views.xml",
        "views/module_popularity_views.xml",
        "views/module_source_type_views.xml",
        "views/product_attribute_views.xml",
        "views/product_odoo_module_menuitems.xml",
        "views/product_product_views.xml",
        "views/product_template_views.xml",
        "views/res_company_views.xml",
        "views/res_partner_views.xml",
    ],
    "installable": True,
}
