from . import customer_module_info
from . import module_business_impact
from . import module_complexity
from . import module_license
from . import module_popularity
from . import module_source_type
from . import product_attribute
from . import product_product
from . import product_template
from . import res_company
from . import res_partner
